### ISSUE TITLE
Cannot build a client

### ISSUE THREAD

**Issue by bermuda-sunfish** [bitwarden/sdk#1028]
### Steps To Reproduce

Borrowing from the documentation:
```
    let settings = ClientSettings {
        identity_url: "https://[my-endpoint]".to_string(),
        api_url: "https://[my-endpoint]".to_string(),
        user_agent: "Bitwarden Rust-SDK".to_string(),
        device_type: DeviceType::SDK,
    };

    let mut client = Client::new(Some(settings));
```
results in 
```
thread 'main' panicked at /Users/b3rmuda/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitwarden-0.5.0/src/client/client.rs:112:60:
Build should not fail: reqwest::Error { kind: Builder, source: "Unknown TLS backend passed to `use_preconfigured_tls`" }
```

My cargo.toml lists the dependencies as:
```
[dependencies]
bitwarden = "0.5.0"
reqwest = { version = "0.12.7", features = [ "http2", "json" ], default_features = false }
rustls-platform-verifier = "0.3.4"
```

The difference from `bitwarden-sdk` is that rustls-platform-verifier = "0.2.0" (fixed in bitwarden-sdk dependencies).  I tried to force setting my local dependency for rustls-platform-verifier = "=0.2.0", but the result was the same. 

As an experiment, I also tried to build a simple `reqwest` client with reqwest-0.12.7 and rustls-platform-verifier-0.2.0, and got the same error. It did work, however, with rustls-platform-verifier-0.3.x. 

I can't seem to find a way to force bitwarden-sdk to be built with rustls-platform-verifier-0.3.x, and I can't seem to find a way in bitwarden sdk to provide my own `ClientBuilder`. What do I do next?

### Expected Result

Expect to successfully build the client. 

### Actual Result

`
thread 'main' panicked at /Users/b3rmuda/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitwarden-0.5.0/src/client/client.rs:112:60:
Build should not fail: reqwest::Error { kind: Builder, source: "Unknown TLS backend passed to `use_preconfigured_tls`" }
`

### Operating System

macOS

### Build Version

0.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by coltonhurst** [comment]
@bermuda-sunfish thanks for the report! Yes, `main` has been updated and we are planning our next release 👍

**Comment by coltonhurst** [comment]
@bermuda-sunfish 1.0 has been released, are you still able to reproduce this?
