### ISSUE TITLE
Broken macOS Universal File in 0.5.0 Release

### ISSUE THREAD

**Issue by jorge-menjivar** [bitwarden/sdk#1046]
### Steps To Reproduce

1. Download https://github.com/bitwarden/sdk/releases/download/bws-v0.5.0/bws-macos-universal-0.5.0.zip from an Intel mac.
2. Try to run. You will get `Bad CPU type in executable`

### Expected Result

To run just like the executable in [bws-x86_64-apple-darwin-0.5.0.zip](https://github.com/bitwarden/sdk/releases/download/bws-v0.5.0/bws-x86_64-apple-darwin-0.5.0.zip) runs.

### Actual Result

`Bad CPU type in executable`

### Additional Context

Judging by the file size, which is the same as aarch64 file, the universal file is probably missing the x84_64 version of the sdk.

### Operating System

macOS

### Shell

Zsh

### Build Version

v0.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @jorge-menjivar,

Thanks for reporting this. This should be resolved by #1052 and will be available soon in the upcoming release.
