### ISSUE TITLE
Can't update secret through JS SDK: 404 Not Found

### ISSUE THREAD

**Issue by phisch** [bitwarden/sdk#1091]
### Steps To Reproduce

Here is an example using the JS SDK to update a secret:
```ts
import {
  BitwardenClient,
  type ClientSettings,
  DeviceType,
  LogLevel,
} from "@bitwarden/sdk-napi";

const BITWARDEN_ACCESS_TOKEN = "**redacted**";

const settings: ClientSettings = {
  apiUrl: "https://api.bitwarden.com",
  identityUrl: "https://identity.bitwarden.com",
  userAgent: "Bitwarden SDK",
  deviceType: DeviceType.SDK,
};

// Can't use LogLevel.Info here, due to:
// SyntaxError: Export named 'LogLevel' not found in module '/**redacted**/node_modules/@bitwarden/sdk-napi/dist/index.js'.
const client = new BitwardenClient(settings, 2);

const result = await client.loginWithAccessToken(BITWARDEN_ACCESS_TOKEN);
if (!result.success) {
  throw Error("Authentication failed");
}

const secret = (
  await client.secrets().get("45036529-9d5c-4dc5-9662-b1f800fd82d9")
).data;

if (!secret) {
  throw Error("Secret not found");
}

const secretUpdateResponse = await client
  .secrets()
  .update(
    secret.id,
    secret.key,
    secret.note,
    secret.organizationId,
    "foo",
  );

console.log(secretUpdateResponse);
```

Sadly, the current SDK seems to be unusable for now.

### Expected Result

I would expect this to update the given secret.

### Actual Result

The response is:
```json
{
  data: null,
  errorMessage: "Received error message from server: [404 Not Found] {\"message\":\"Resource not found.\",\"validationErrors\":null,\"exceptionMessage\":null,\"exceptionStackTrace\":null,\"innerExceptionMessage\":null,\"object\":\"error\"}",
  success: false,
}
```

Aside from that, it's also not possible to use `LogLevel.Info` as described on the npm package: https://www.npmjs.com/package/@bitwarden/sdk-napi
Since using that causes a syntax error:
```
SyntaxError: Export named 'LogLevel' not found in module '/**redacted**/node_modules/@bitwarden/sdk-napi/dist/index.js'.
```

### Operating System

Linux

### Build Version

"@bitwarden/sdk-napi": "^0.3.1",

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by coltonhurst** [comment]
@phisch we recently released `1.0` on NPM here: https://www.npmjs.com/package/@bitwarden/sdk-napi

Can you please try the latest version? I also have an example project and can use the SDK successfully: https://github.com/coltonhurst/bw-napi-test

**Comment by phisch** [comment]
@coltonhurst Hey, we have since switched to an alternative. So we don't use the bitwarden secrets manager anymore. I'll leave it open in case you want to test yourself.

**Comment by coltonhurst** [comment]
No worries, thanks for the response. I believe we are all good so I'll close this.

**Comment by psteinroe** [comment]
hey @coltonhurst , having the same issue in v1.0.0. this throws resource not found:

```tsx
      const newSecret = await this.bitwarden
        .secrets()
        .create(
          this.opts.organisationId,
          key,
          secretValue,
          note || 'MANAGED BY CI',
          [projectId]
        );
```

I fetched the `projectId` using this before, so it must exist!

```tsx
    const settings = await this.bitwarden
      .projects()
      .list(this.opts.organisationId);
```

**Comment by psteinroe** [comment]
> hey [@coltonhurst](https://github.com/coltonhurst) , having the same issue in v1.0.0. this throws resource not found:
> 
>       const newSecret = await this.bitwarden
>         .secrets()
>         .create(
>           this.opts.organisationId,
>           key,
>           secretValue,
>           note || 'MANAGED BY CI',
>           [projectId]
>         );
> I fetched the `projectId` using this before, so it must exist!
> 
>     const settings = await this.bitwarden
>       .projects()
>       .list(this.opts.organisationId);

nevermind - the access token did not have write access!
