### ISSUE TITLE
Missing linux version in the NAPI SDK v1.0.0 release

### ISSUE THREAD

**Issue by chelyabinsk** [bitwarden/sdk#1101]
### Steps To Reproduce

1. Go to [Releases](https://github.com/bitwarden/sdk/releases/tag/napi-v1.0.0)
2. Click on Assets
3. Scroll down to the bottom
4. Observe that only Source code .zip / .tar.gz are present

### Expected Result

I would expect similar pattern to other releases that have files for different platforms like
`bws-aarch64-apple-darwin-1.0.0.zip `

`bws-aarch64-pc-windows-msvc-1.0.0.zip `

### Actual Result

Only source code files are present in the release

### Operating System

Linux

### Shell

Bash

### Build Version

N/A

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tangowithfoxtrot** [comment]
Hi, @chelyabinsk.

You may have encountered the missing node files while we were in the middle of a release and all of the artifacts hadn't been uploaded yet. You should be able to download the Node artifacts for the supported artifacts now from the [Releases page](https://github.com/bitwarden/sdk/releases/tag/napi-v1.0.0) now.

Regarding the naming of the artifacts, we'll leave #1110 open to track that.
