### ISSUE TITLE
Multiple "The type or namespace name <type> could not be found (are you missing a using directive or an assembly reference?)"

### ISSUE THREAD

**Issue by frenchap** [bitwarden/sdk#1128]
### Steps To Reproduce

1. Go to SecretsClient.cs
2. See there no type defined for Command, SecretResponse, or SecretCommand.
3. There are several other types across the C-sharp code

### Expected Result

Expect no errors reading "The type or namespace name <type> could not be found (are you missing a using directive or an assembly reference?)"

### Actual Result

Received at three "The type or namespace name <type> could not be found (are you missing a using directive or an assembly reference?)"

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/d342b053-c5bd-4531-ad9f-cdcd99d980fb)

### Operating System

Windows

### Operating System Version

11

### Build Version

1.0.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by coltonhurst** [comment]
Hey @frenchap, if you want to build C# from source within the SDK, you will need to generate the schema files. Please try the following:

1. Clone the SDK repository and `cd` to the SDK root
2. `cargo build`
3. `npm ci`
4. `npm run schemas`

That should generate the files with the missing types. Please reopen if you run into any issues 😄

**Comment by frenchap** [comment]
@coltonhurst, thank you for your quick response.  I will try this and let you know if it works.

**Comment by frenchap** [comment]
@coltonhurst, working great, thanks for your help

**Comment by findyoucef** [comment]
This information should be added to the README.
