### ISSUE TITLE
 @bitwarden/sdk-napi: Unsupported OS: aix, architecture: ppc64

### ISSUE THREAD

**Issue by cole-maxwell1** [bitwarden/sdk#171]
### Steps To Reproduce

1. Access a secret via nodejs binding from @bitwarden/sdk-napi on an AIX platform device.

### Expected Result

Successful access of a secrete stored in the secretes manager.

### Actual Result

```sh 
/home/colem/secrets-manager-tests/node_modules/@bitwarden/sdk-napi/binding.js:211
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
          ^

Error: Unsupported OS: aix, architecture: ppc64
    at Object.<anonymous> (/home/colem/secrets-manager-tests/node_modules/@bitwarden/sdk-napi/binding.js:211:11)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/colem/secrets-manager-tests/node_modules/@bitwarden/sdk-napi/dist/bitwarden_client/index.js:36:27)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
```

### Additional Context

Hi, I was evaluating the SDK for usage at work and wanted to draw your attention to this. We run a number of nodejs applications on IBMi systems in the AIX portion of the OS. I would really like to bring this solution into our environment, but this is a show-stopper for us. 

Rust does provide [Tier 3](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3) support for `powerpc64-ibm-aix` but I understand that this might be a difficult platform to support. I would be willing to help test any solution.

### Operating System

Linux

### Operating System Version

IBMi 7.4 (AIX)

### Build Version

0.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @cole-maxwell1,

I looked at the Tier 3 table and it seems the powerpc64-ibm-aix `std` support is "standard library support is unknown or a work-in-progress". We rely on the standard library for a few things which might make this slightly troublesome. 

There also doesn't seem to be any way to cross-compile at this moment which means we won't have any way to actually build binaries in our CI at the moment, https://github.com/rust-lang/rust/pull/114316/files#diff-1a0b4be2cbce53028de3e544a1f4701143c40ebb6d8ab0c19deae4ce602b3786.

With that said, we are experimenting with supporting WebAssembly which would bring support for more architectures (presuming WASM is supported by the node.js build). However it's not our highest priority at the moment.

In the meanwhile you could try compiling the `bitwarden-napi` package yourself using 
```bash
cd crates/bitwarden-napi
npm ci
npx napi build --target powerpc64-ibm-aix --platform --release --js binding.js --dts binding.d.ts && npx tsc
```
I'm also unsure if the Node-API tool we use supports powerpc out of the box so you might need to manually edit `binding.js` to load the powerpc binary.


Hope this is a bit of a help.

**Comment by cole-maxwell1** [comment]
@Hinton Thanks for having a look!
