### ISSUE TITLE
404 when trying to access my secrets or projects in EU

### ISSUE THREAD

**Issue by satabin** [bitwarden/sdk#209]
### Steps To Reproduce

1. Install bws CLI 0.3.0 for Linux from the [release download section](https://github.com/bitwarden/sdk/releases/tag/bws-v0.3.0)
2. Create a project with a secret, a service account on an account at bitwarden.eu
3. Give read access to the project for the service account
4. Generate a token for the service account
5. Run `bws project list -u https://api.bitwarden.eu -t <my-token>` 

### Expected Result

See the created project to which the service account has access.

### Actual Result

```
Error:
   0: Received error message from server: [404 Not Found]

Location:
   crates/bws/src/main.rs:307

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### Additional Context

The same happens with secret listing or accessing a concrete secret.
If I provide an invalid token I get an authentication error, so I assume the token is valid.

### Operating System

Linux

### Operating System Version

Debian 12.1

### Shell

Zsh

### Build Version

Bitwarden Secrets CLI 0.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dani-garcia** [comment]
Can you try running the command `bws project list -u https://vault.bitwarden.eu -t <my-token>` instead? (Changing `api` for `vault` in the URL)

**Comment by satabin** [comment]
It worked indeed. I was confused by the documentation which mentions `api`. Thanks.
