### ISSUE TITLE
Make available for Raspberry Pi arm64

### ISSUE THREAD

**Issue by 0lzi** [bitwarden/sdk#31]
### Steps To Reproduce

1. No available binary 

Tried downloading the Apple aarch64 and get `cannot execute binary file: Exec format error`

### Expected Result

Expect a arch64 or armhf binary and be able to use bws commands

### Actual Result

no aarch64 / armhf binary

### Additional Context

Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT aarch64 GNU/Linux

### Operating System

Linux

### Operating System Version

rapperypi OS

### Shell

Bash

### Build Version

na

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @0lzi,

The darwin aarch64 build is unfortunately not compatible with linux, they use different standard libraries. I did look into enabling cross compiling for the linux build but ran into some issues that will require some more extensive work to resolve.

In the meanwhile it should be possible to compile the CLI yourself using `cargo install bws` if you have the rust toolchain installed.
