### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by tnkemdilim** [bitwarden/sdk#36]
### Steps To Reproduce

There's currently no function exposed to create a project from the SDK.

### Expected Result

I'll expect that not only should a project be created, but that the service account access token should have read permission to the project automatically - unless configured otherwise.

### Actual Result

No function exposed to fetch create a project.

### Operating System

macOS

### Build Version

0.2.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
This was implemented in https://github.com/bitwarden/sdk/pull/53 & https://github.com/bitwarden/sdk/pull/67 and should be included in the next release for the SDK and CLI.
