### ISSUE TITLE
`--color no` not respected for errors

### ISSUE THREAD

**Issue by jantari** [bitwarden/sdk#50]
### Steps To Reproduce

Run `bws --color no --access-token whatever get secret whatever` with bws CLI 0.2.1

### Expected Result

The output should not contain terminal escape sequences / color.

### Actual Result

The output contains terminal escape sequences and color text.

### Screenshots or Videos

![grafik](https://github.com/bitwarden/sdk/assets/25607767/530888b1-90df-4969-bc55-1dcf1183b2d3)

### Additional Context

This behavior is unexpected and makes it unneccessarily difficult to capture a "clean" output of the command for logging purposes, or for output to a non-terminal.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04 WSL

### Shell

Bash

### Build Version

0.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
HI @jantari,

Thanks for reporting this. I agree this seems like undesired behavior and we'll need to figure out a way to disable the colors of the errors.
