### ISSUE TITLE
Using bws cli on Windows Server 2012 failing with os error code -2146893018.

### ISSUE THREAD

**Issue by mschaefer-gresham** [bitwarden/sdk#719]
### Steps To Reproduce

- Download latest `bws` onto a Windows Server 2012 R2 machine.
- Create BWS_ACCESS_TOKEN env variable
- Run `bws list projects`

### Expected Result

[
  {
    "id": "my-id",
    "organizationId": "my-org-id",
    "name": "my-prpject-name",
    "creationDate": "2023-05-26T09:04:22.914031600Z",
    "revisionDate": "2023-05-26T09:04:22.914031700Z"
  }
]

### Actual Result

C:\dev\>bws list projects
Error:
   0: ←[91merror sending request for url (https://identity.bitwarden.com/connect/token): error trying to connect: The message received was u
nexpected or badly formatted. (os error -2146893018)←[0m
   1: ←[91merror trying to connect: The message received was unexpected or badly formatted. (os error -2146893018)←[0m
   2: ←[91mThe message received was unexpected or badly formatted. (os error -2146893018)←[0m

Location:
   ←[35mcrates\bws\src\main.rs←[0m:←[35m334←[0m

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

### Additional Context

The error code -2146893018 typically indicates a problem related to cryptographic operations on Windows systems. Specifically, it often corresponds to errors with cryptographic functions like those used for SSL/TLS connections or certificate operations.

I've tested on a Mac, and Windows 11, and Windows Server 2019, and it works fine. 

### Operating System

Windows

### Operating System Version

2012 R2

### Build Version

0.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @mschaefer-gresham,

Error code `-2146893018` is `0x80090326` which generally indicates an issue negotiating TLS certificates. Most likely the windows 2012 build doesn't support modern TLS cipher suites and needs to be updated. You can investigate if there are available updates for Windows Server 2012 that supports the required cipher suites or if there are other ways to enable it. Unfortunately windows 2012 is end of life and Microsoft may not have backported the required updates.

I suspect you are unable to access the bitwarden web vault either due to this same issue.

**Comment by mschaefer-gresham** [comment]
@Hinton yes, but this is caused by a change Bitwarden has made. This was working fine within the last two days. Was there an announcement that you would stop supporting older encryption methods (or whatever the cause is)?

**Comment by Hinton** [comment]
Hi @mschaefer-gresham,

I wasn't aware this was a recent change as that wasn't mentioned in your initial issue. I've pinged the relevant team internally which is looking into it.

That said this isn't really the best channel for these type of issues, as it's related to our cloud infrastructure which is typically best handled by our support team at https://bitwarden.com/contact/.

**Comment by mschaefer-gresham** [comment]
@Hinton I received this explanation from the support team:

Hi Matthew,
 
​My name is Keith and I work in the integration team at Bitwarden, pleased to meet you!
 
I wanted to give you some more information on this. We have recently upgraded some of our security architecture which has resulted in the problem you have. Windows Server went EOL in October 2023 and therefore has been impacted by this change, as this product is EOL we hadn't intended to support this. I apologise that this has caused you issues, I will ensure we reach out to the product team to ensure better communication of breaking changes to older products to ensure customers have time to migrate to supported environments. 
​
​Kind regards,
​Keith
