### ISSUE TITLE
exe file is not installing

### ISSUE THREAD

**Issue by kkeles** [bitwarden/sdk#773]
### Steps To Reproduce

1. Go to releases
2. Click on 0.5.0
3. Install bws.exe
4. Click on bws.exe
Nothing happens

### Expected Result

It should normally compile and install the CLI into usage.

### Actual Result

I try to install the CLI on my Windows machine but nothing happens

### Operating System

Windows

### Shell

Bash

### Build Version

0.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @kkeles,

Please review our help documentation on the CLI, https://bitwarden.com/help/secrets-manager-cli/. There should be nothing to install, simply download the appropriate build, which for windows is `bws-x86_64-pc-windows-msvc-0.5.0.zip`. Unzip, and run from the terminal or command prompt. Do note that clicking on the executable would just quickly open a terminal window before immediately closing it.

If you need more assistance please reach out to our support team, using the "contact support" button in the help center.
