### ISSUE TITLE
bitwarden/sm-sdk-go isn't public

### ISSUE THREAD

**Issue by sylwit** [bitwarden/sdk#800]
### Steps To Reproduce

1. Access the go sdk README and follow Initialisation step : https://github.com/bitwarden/sdk/blob/main/languages/go/README.md#initialization

2. Try to get the sdk "go get github.com/bitwarden/sm-sdk-go"
3. https://github.com/bitwarden/sm-sdk-go returns a 404

### Expected Result

SDK should be accessible

### Actual Result

https://github.com/bitwarden/sm-sdk-go returns a 404

### Additional Context

Looks like the go-sdk is a private repo.

We can see in github action the go sdk release which checkout the repo https://github.com/bitwarden/sdk/actions/runs/9192915122/job/25282753536.

I wonder if there is any reason for this repo to be private, or should the README be updated ?

Thank you

### Operating System

Linux

### Build Version

NA

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by addvanced** [comment]
Got the same issue.
I guess a temporary workaround is to download the content of github.com/bitwarden/sdk/languages/go, and place it in the your project, and replace it in the go.mod file for now.

**Comment by sylwit** [comment]
@addvanced this could work in a personal project or working locally but it won't be accepted in an open source project.

There is an open PR to make thus sdk usable because currently it's not. https://github.com/bitwarden/sdk/pull/647#issuecomment-2132075707

**Comment by coltonhurst** [comment]
@sylwit nice eye! We actually are in the middle of working on this now, and hope to have this open very soon 🙂

**Comment by coltonhurst** [comment]
@sylwit @addvanced you should be able to view the Go repository now: https://github.com/bitwarden/sdk-go

We will be adding more docs soon as well 😄

**Comment by sylwit** [comment]
Awesome. Thank you @coltonhurst
