### ISSUE TITLE
invalid_client on ApiKey authentication for C# S

### ISSUE THREAD

**Issue by pedrodel99** [bitwarden/sdk#925]
### Steps To Reproduce

Use secret manager on bitwarden.eu then use this code using C# SDK.
`
var bitwardenClient = new BitwardenClient(new BitwardenSettings()
{
	ApiUrl = "https://api.bitwarden.eu",
});

bitwardenClient.AccessTokenLogin("<access-token>"));
`

### Expected Result

Connection was suppose to be made...

### Actual Result

Thrown exception `Bitwarden.Sdk.BitwardenAuthException: 'Received error message from server: [400 Bad Request] {"error":"invalid_client"}'`

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/3f00a909-bf05-4fb2-8f9c-e81bae79c2b9)

### Operating System

Windows

### Build Version

0.0.1-alpha1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dani-garcia** [comment]
Hey there!

This seems similar to this older bug report https://github.com/bitwarden/sdk/issues/209.

Can you try setting `ApiUrl = "https://vault.bitwarden.eu"` and let me know if that solves your issue? Thanks!

**Comment by coltonhurst** [comment]
Hey @pedrodel99 please feel to re-open if you run into the same issue again 😊
