### ISSUE TITLE
@bitwarden/sdk-client is not published on npm

### ISSUE THREAD

**Issue by Araxeus** [bitwarden/sdk#943]
### Steps To Reproduce

Your example https://github.com/bitwarden/sdk/blob/main/languages/js/example/index.js
says
```js
const sdk = require("@bitwarden/sdk-client");
```
but https://www.npmjs.com/package/@bitwarden/sdk-client doesn't exist

What I really don't understand is that you have a package like that on github, and it is maintained!

https://github.com/bitwarden/sdk/tree/main/languages/js/sdk-client

what is going here? am i missing something? @dani-garcia 

### Expected Result

the build workflow should include a publish to npm step for `@bitwarden/sdk-client`

### Actual Result

there is only a publish step for `@bitwarden/sdk-wasm`

https://github.com/bitwarden/sdk/blob/6f98c33c065fee5b6af3968f5990049de02acc7a/.github/workflows/build-wasm.yml#L71-L76

### Operating System

Windows

### Build Version

.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
HI @Araxeus,

The `main` is pointing to in-development work and the examples are configured to represent a state where they can be run against the development version. The sdk-client and sdk-wasm are unreleased as of now, since wasm lacks some capabilities we desire to use.

The currently released Node.js SDK is https://www.npmjs.com/package/@bitwarden/sdk-napi, which lives in https://github.com/bitwarden/sdk/tree/main/crates/bitwarden-napi. The npmjs page includes documentation on usage, and the https://github.com/bitwarden/sm-action/ is a more complex example of how it can be used.

**Comment by Araxeus** [comment]
I dont understand. all your documentation points to @bitwarden/wasm

why did you change all your documentation to this sdk if its not working!??!

![image](https://github.com/user-attachments/assets/df14b600-05fb-4dc7-aee9-45857b0ee235)

https://bitwarden.com/products/secrets-manager/

https://bitwarden.com/help/secrets-manager-sdk/

# there is no mention of @bitwarden/napi in your documentation!

**Comment by Hinton** [comment]
Hi @Araxeus,

I'm not sure why the documentation is referencing the unreleased wasm library. I've reached out to the team to investigate and address the documentation. As of right now only the napi sdk is released and usable.

**Comment by Araxeus** [comment]
The links I provided still reference and link to the wasm lib

**Comment by jazoom** [comment]
Yup. This is still confusing. The documentation only mentioned the unreleased project.

**Comment by fritz-fritz** [comment]
This also confused me. Searching the closed issues to find this answer when the dashboard links to the unfinished wasm port is frustrating. It's also frustrating that the latest stable build from over a year ago is incompatible with webpack and hence can't be used from an edge environment (but that's another issue). I love bitwarden... but seems like they need to hire someone to work on sdk and docs if they truly want the secret manager to actually be useful
