### ISSUE TITLE
Missing bitwarden_c.dll

### ISSUE THREAD

**Issue by Nibroc00** [bitwarden/sdk#988]
### Steps To Reproduce

1. `go get github.com/bitwarden/sdk-go`
2. Import sdk "github.com/bitwarden/sdk-go" into project
3. `go install` project
4. Run binary
5. Result "error while loading shared libraries: bitwarden_c.dll: cannot open shared object file: No such file or directory"

Here's my `go env`:
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\CorbinPark\AppData\Local\go-build
set GOENV=C:\Users\CorbinPark\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\CorbinPark\go\pkg\mod
set GONOPROXY=gitlab.com/komodo-systems/*
set GONOSUMDB=gitlab.com/komodo-systems/*
set GOOS=windows
set GOPATH=C:\Users\CorbinPark\go
set GOPRIVATE=gitlab.com/komodo-systems/*
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\CorbinPark\Projects\sdk-go\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\CORBIN~1\AppData\Local\Temp\go-build2575380933=/tmp/go-build -gno-record-gcc-switches

### Expected Result

Bitwarden sdk to import and be usable by my Go package

### Actual Result

I recieve this error:
"error while loading shared libraries: bitwarden_c.dll: cannot open shared object file: No such file or directory"

### Additional Context

Apologies if I am missing something obvious, and thank you in advance.

### Operating System

Windows

### Operating System Version

Windows 11

### Build Version

0.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Nibroc00** [comment]
Side note the only thing I can find similar to the missing file is: 

- /bitwarden/sdk-go@v0.1.1/internal/cinterface/lib/windows-x64/libbitwarden_c.a
- /bitwarden/sdk-go@v0.1.1/internal/cinterface/lib/windows-x64/libbitwarden_c.dll.a

Yet from what I can find the sdk looks for the wrong name:
https://github.com/search?q=repo%3Abitwarden%2Fsdk%20.dll&type=code

**Comment by coltonhurst** [comment]
@Nibroc00 the new `1.0.2` release should fix this, can you please try again?

**Comment by coltonhurst** [comment]
Closing, @Nibroc00 please feel free to open this if you are still running into issues!

**Comment by debojyoti452** [comment]
Nope it's still persists

**Comment by debojyoti452** [comment]
exit status 0xc0000135 -> getting this error

**Comment by coltonhurst** [comment]
@debojyoti452 thanks for letting us know. I will let the appropriate team know internally.

Can you provide more information about your system and your reproduction steps?
